### PR TITLE
📖 Added CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by derekkramer**

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/nodejs-http-client?pullRequest=12) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/nodejs-http-client?pullRequest=12) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/nodejs-http-client?pullRequest=12) it.</sub>

**Comment by thinkingserious** [comment]
Hello @derekkramer,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by mbernier** [comment]
@derekkramer 
If you are interested, we would love the opportunity to talk to you about Hacktoberfest and our API libraries.

Our agenda would be: Explore what you liked and is there anything we can do to improve? 

You can grab a time [on my calendar](https://calendly.com/matt-bernier/hacktoberfest-follow-up) that works for you and we can have a chat on Google Hangout or Skype. If you prefer, you can email me using my GitHub username at my company’s domain.

Thank you so much,

Matt Bernier - @mbernier - SendGrid Developer Experience Product Manager
Elmer Thomas - @thinkingserious - SendGrid Developer Experience Engineer
@SendGrid

**Comment by derekkramer** [comment]
Team SendGrid DX,

I’m emailing regarding the special edition swag that you offered to contributors during Hacktoberfest 2017. I contributed to one of your repos on GitHub and received notice that my pull request was merged. I haven’t yet received the swag however, I was wondering if that was still in the process of being sent or if I may have been missed in the list of contributors. Thanks!

Best,
Derek

_____________________________

Derek Kramer

  (303) 506-8669
  derekdevelops@gmail.com
  derekkramer.co
  linkedin.com/in/derek-kramer
  github.com/derekkramer

**Comment by mbernier** [comment]
@derekkramer Did you fill out the swag form on your PR? If so, the swag is coming - we had such a large response that we had to do another order and get it to our fulfillment house, so that we could send out what was promised.

**Pull request merged**
