### PR TITLE
Fixes #13: Adds TROUBLESHOOTING.md

### LINKED ISSUE #13: Demonstrate how to review the request body for troubleshooting
When debugging, it can be useful to examine the request body before sending to the SendGrid API.

Prove an example of how to examine the request body in TROUBLESHOOTING.md. For an example, see [here](https://github.com/sendgrid/sendgrid-python/blob/master/TROUBLESHOOTING.md#request-body).

### PR DESCRIPTION
**Pull request by narayanaditya95**
Fixes #13

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/nodejs-http-client?pullRequest=31) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/nodejs-http-client?pullRequest=31) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/nodejs-http-client?pullRequest=31) it.</sub>

**Comment by mbernier** [comment]
Hey @narayanaditya95 it looks like #30 beat you to it by minutes, I am sorry about that!

**Comment by narayanaditya95** [comment]
Sorry to be picky but #30's commit is after mine.

screen shot 2017-10-24 at 8 51 09 am

The commit happened after the label was added, which happened at 11:40+05.30. My commit was pushed at 11:32+05.30. Moreover, his commit is largely inspired from mine. The original commit had no headers or TOC.

**Comment by mukulmishra18** [comment]
> #30's commit is after mine.

It appears after the label because I squashed the commits after adding some more code(when I looked into other [TROUBLESHOOTING.md](https://github.com/sendgrid/python-http-client/blob/master/TROUBLESHOOTING.md) file), so that PR does not look noisy. Please refers https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History to learn about squashing commits.

**Comment by narayanaditya95** [comment]
I know you squashed commits. My point still holds. But nevermind.

**Pull request closed without merging**
