### PR TITLE
Adds code of conduct

### PR DESCRIPTION
**Pull request by geekyd**
Fixes: #10 

Adds CODE_OF_CONDUCT.md to the project

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/nodejs-http-client?pullRequest=11) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/nodejs-http-client?pullRequest=11) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/nodejs-http-client?pullRequest=11) it.</sub>

**Comment by geekyd** [comment]
@thinkingserious I have signed the CLA. Please review

**Comment by thinkingserious** [comment]
Hello @geekyd,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by geekyd** [comment]
@thinkingserious
I have filled the form. Thanks for the update.

**Pull request merged**
