### PR TITLE
Idiomatic changes reported by CodeClimate

### LINKED ISSUE #49: idiomatic changes needed, as reported by CodeClimate
#### Issue Summary

CodeClimate is watching our repo and has reported some specific changes to the code, can you please fix these up?

https://codeclimate.com/github/sendgrid/nodejs-http-client/pull/48

### PR DESCRIPTION
**Pull request by mithunsasidharan**
# Fixes #49

### Checklist
- [ ] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [ ] I have read the [Contribution Guide] and my PR follows them.
- [ ] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

### Short description of what this PR does:
- 
- 

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/nodejs-http-client?pullRequest=61) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/nodejs-http-client?pullRequest=61) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/nodejs-http-client?pullRequest=61) it.</sub>

**Comment by mbernier** [comment]
Codeclimate is happy.
The build is not failing due  to your change, it's because files are missing - we added the tests before the files were created :)

**Comment by thinkingserious** [comment]
Hello @mithunsasidharan,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by mithunsasidharan** [comment]
@thinkingserious : Thank you.. When i submit the swag form, I get the message **I don't know who you are; I should, but regretfully I don't.** ?

**Comment by mbernier** [comment]
@mithunsasidharan Please try going to https://dx.sendgrid.com/swag [in incognito mode](https://www.laptopmag.com/articles/how-to-use-incognito-windows-in-chrome) and logging in using github. My guess is that something went goofy with our page and the github token in your browser.

**Comment by mithunsasidharan** [comment]
@mbernier : I tried incognito and also from another browser with a fresh github login but its the same message 😞 ! Can you help ?

**Comment by mbernier** [comment]
One last check - did you make sure that you signed into Github from your `mithunsasidharan` user? We have seen some people who have 2 github users have issues. 

If that doesn't work, please send me an email [my github handle at this repo's organization dot com] and we'll make sure you're taken care of.

**Comment by mithunsasidharan** [comment]
@mbernier : I just have a single github account and 1 enterprise github account.. but thats a different domain so I don't think thats got anything to do with this. I confirmed that the email used in the CLA is also the same email that I use for my github account.

**Comment by mithunsasidharan** [comment]
@mbernier :  I tried from my mobile too but no luck. I'll drop a mail to you with details ! Thanks much.

**Comment by thinkingserious** [comment]
@mithunsasidharan,

My apologies! The form has been repaired, could you please try again? Thank you!

With Best Regards,

Elmer

**Comment by mithunsasidharan** [comment]
@thinkingserious : it worked this time! Thanks for the prompt support 👍

**Pull request merged**
