### PR TITLE
Updated travis config

### LINKED ISSUE #21: Update Travis.yml to use supported node versions
#### Issue Summary

The nodeJS releases site shows that .10 and .12 are no longer supported. They also show some major builds that are supported. Please update Travis.yml accordingly.

Example: https://github.com/sendgrid/smtpapi-nodejs/pull/37

### PR DESCRIPTION
**Pull request by gr8shivam**
Fixes #21

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/nodejs-http-client?pullRequest=22) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/nodejs-http-client?pullRequest=22) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/nodejs-http-client?pullRequest=22) it.</sub>

**Comment by mbernier** [comment]
Blocked by #25

**Comment by mbernier** [comment]
@rasjani I just noticed this was the PR you mentioned was in before yours
Do you mind giving this a once over to see what's causing this to fail?  It seems like your build was working?

**Comment by mbernier** [comment]
Looks like it's building now!

**Comment by thinkingserious** [comment]
Hello @gr8shivam,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/announcing-hacktoberfest-2017">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
