### PR TITLE
Adds test to check license end year.

### LINKED ISSUE #51: Add a unittest to check the license.md file date range
The end year in the license file should be "this year" and this should be checked on every run of the tests. If the end year is no correct, fail the test.
example: 
> Copyright (c) 2012-2016 SendGrid, Inc.
It is 2017, so this should be:
> Copyright (c) 2012-2017 SendGrid, Inc.
and the  test should fail.
--done

### PR DESCRIPTION
**Pull request by mukulmishra18**
Fixes #51 

Please note that added test is failing right now, as `LICENSE.txt` file does not have correct end year. Also this test expects the year in range(i.e. `2016-2017`), but only contains `2016`. Maybe fix after #53

### CODE REVIEW

**Comment by mukulmishra18** [comment]
Hi @mbernier, I have updated the PR to new master and it is passing `LICENSE` test locally, Thanks.

**Comment by mbernier** [comment]
There was a merge conflict and an extra parenthesis on line 321, looked like this:
```
  function fileExists(filepath) {
    try {
      return fs.statSync(filepath).isFile();
    } catch(e) {
      if (e.code === 'ENOENT') {
        console.log('' + filepath + ' doesn\'t exist.');
        return false;
      }
      throw e;
    }
  })
})
```
it is now this:
```
  function fileExists(filepath) {
    try {
      return fs.statSync(filepath).isFile();
    } catch(e) {
      if (e.code === 'ENOENT') {
        console.log('' + filepath + ' doesn\'t exist.');
        return false;
      }
      throw e;
    }
  } //no paren here any longer
})
```

**Comment by thinkingserious** [comment]
@flaredragon

We have not been able to merge your Pull Request, but because you are awesome - we wanted to make sure you could still get a SendGrid Hacktoberfest shirt.  

Please go **fill [out our swag form](https://dx.sendgrid.com/swag) before Nov 5th** and we will send the shirt! (We know that you might have tried this before and it didn’t work, sorry about that!)

### **You have till Nov 5th to fill out this form** in order to get the Hacktoberfest shirt!

Thank you for contributing during Hacktoberfest! We hope to see you in the repos soon! Just so you know, we always give away a SendGrid shirt for your first ever non-Hacktoberfest PR that gets merged.

**Comment by flaredragon** [comment]
@thinkingserious Thanks a Lot!
My PR in another repository was merged during Hacktoberfest So I have filled the form before.

**Comment by mukulmishra18** [comment]
I think it should be fine now. @mbernier can you please have a look?

**Comment by thinkingserious** [comment]
Thanks @mukulmishra18! 

Your PR is now scheduled for review :) Please bear with us as we have fallen behind on our reviews due to the 1,000+ PRs in October.

Big thanks Forbes your contribution and patience.

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hello @mukulmishra18,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Comment by mbernier** [comment]
If you are interested, we would love the opportunity to talk to you about Hacktoberfest and our API libraries.

Our agenda would be: Explore what you liked and is there anything we can do to improve? 

You can grab a time [on my calendar](https://calendly.com/matt-bernier/30min) that works for you and we can have a chat on Google Hangout or Skype. If you prefer, you can email me using my GitHub username at my company’s domain.

Thank you so much,

Matt Bernier - @mbernier - SendGrid Developer Experience Product Manager
Elmer Thomas - @thinkingserious - SendGrid Developer Experience Engineer
@SendGrid

**Pull request merged**
