### PR TITLE
[issue#52] Added unit tests to check some files exist

### PR DESCRIPTION
**Pull request by luan-cestari**
**Description of the change**:
This PR fulfill the request from issue #52 , which asked to create tests to validate if some files exist

**Reason for the change**:
The reason behind the request is guarantee that some basic files like README.MD will always be present int he project, so, if it is erased by mistake, the tests will not pass and it will be explicit the problem, without any human manual validation 

**Link to original source**:
The actual source https://github.com/sendgrid/nodejs-http-client/blob/90ca4ebb6e0e6b59bd554908105f66114ad5a8f6/test/test.js

### Checklist

Make sure all of these items are complete, or else the PR will be ineligible for a code review.

- [x] Code passes all existing [tests](https://github.com/sendgrid/nodejs-http-client/tree/master/test) **the new tests do not pass as it is expected mentioned in #52** 
- [x] Any new functionality added includes new unit tests in [`test/test.js`](https://github.com/sendgrid/nodejs-http-client/tree/master/test/test.js)
- [x] Create or update example code to show the new functionality in action.
- [x] All code, branch, and git naming and style conventions are followed (see [`CONTRIBUTING.md`](https://github.com/sendgrid/nodejs-http-client/blob/master/CONTRIBUTING.md#style-guidelines--naming-conventions))
- [x] Feature branch has been rebased off of the latest `master` branch. ( see [`CONTRIBUTING.md`](https://github.com/sendgrid/nodejs-http-client/blob/master/CONTRIBUTING.md#creating-a-pull-request) ).

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/nodejs-http-client?pullRequest=55) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/nodejs-http-client?pullRequest=55) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/nodejs-http-client?pullRequest=55) it.</sub>

**Comment by mbernier** [comment]
BEAUTIFULLY done! 

This is awesome. Thank you so much!! 

Just so you know, we have this same issue on another Node library if you're interested:
- https://github.com/sendgrid/sendgrid-nodejs/issues/565

**Comment by thinkingserious** [comment]
Hello @luan-cestari,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by luan-cestari** [comment]
Thank you guys =) I hope I can help with other issues in the future

**Pull request merged**
