### PR TITLE
added code climate config fixes #47

### LINKED ISSUE #47: Add a .codeclimate.yml file to this repo
It is possible to configure how CodeClimate looks at a repository.
[These Docs](https://docs.codeclimate.com/docs/getting-started-configuration) explain how this is done. Please create an appropriate .codeclimate.yml for this repo. It should test the main language of the repo and run tests.

### PR DESCRIPTION
**Pull request by t2013anurag**
Added code climate configuration.

The title should be descriptive, for example:
Fixes #47 

### Checklist

Make sure all of these items are complete, or else the PR will be ineligible for a code review.
- [x] Code passes all existing [tests](https://github.com/sendgrid/nodejs-http-client/tree/master/test)
- [x] Any new functionality added includes new unit tests in [`test/test.js`](https://github.com/sendgrid/nodejs-http-client/tree/master/test/test.js)
- [x] Create or update example code to show the new functionality in action.
- [x] All code, branch, and git naming and style conventions are followed (see [`CONTRIBUTING.md`](https://github.com/sendgrid/nodejs-http-client/blob/master/CONTRIBUTING.md#style-guidelines--naming-conventions))
- [x] Feature branch has been rebased off of the latest `master` branch. ( see [`CONTRIBUTING.md`](https://github.com/sendgrid/nodejs-http-client/blob/master/CONTRIBUTING.md#creating-a-pull-request) ).

If you have questions, please send an email [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/nodejs-http-client?pullRequest=48) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/nodejs-http-client?pullRequest=48) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/nodejs-http-client?pullRequest=48) it.</sub>

**Comment by t2013anurag** [comment]
@thinkingserious - Codeclimate tests will fail because of eslint fixes.

**Comment by t2013anurag** [comment]
@mbernier @thinkingserious  - updated the PR.

**Comment by mbernier** [comment]
Thank you!!!!!

**Comment by thinkingserious** [comment]
Hello @t2013anurag,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/announcing-hacktoberfest-2017">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
