### PR TITLE
Refactored unittest to check for specific repo files to use assert

### LINKED ISSUE #57: Assert file exists
#### Issue Summary

@mptap I am curious if you would be interested in switching these if statements over to test assertions? https://github.com/sendgrid/nodejs-http-client/blob/master/test/test.js 

I really like how the tests you created in https://github.com/sendgrid/smtpapi-nodejs/pull/60 ended up displaying in Travis. That would be amazing to have here too.

### PR DESCRIPTION
**Pull request by mptap**
# Fixes #57

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

### Short description of what this PR does:
- Refactored unittest to check for specific repo files to use assert

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

@mbernier edit - removed extra '#' in title

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/nodejs-http-client?pullRequest=58) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/nodejs-http-client?pullRequest=58) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/nodejs-http-client?pullRequest=58) it.</sub>

**Comment by mbernier** [comment]
@mptap I have to apologize, I know you signed the CLA on another of our repos, but our legal team is funny and would like people to sign it for each repo they contribute to. Is that OK?

**Comment by mptap** [comment]
@mbernier: No worries, I understand :) Signed.

**Comment by mptap** [comment]
@mbernier: Whoops, had a missing closing brace, updated.

**Comment by mbernier** [comment]
I merged in the master branch, because I believe most of the files we're checking for exist now :)

**Comment by mptap** [comment]
@mbernier: I see. I've signed the CLA for this repo though - when I click on it, it says `You have signed the CLA for sendgrid/nodejs-http-client`. Tried clicking on `Let us recheck it` - no joy.

**Comment by mbernier** [comment]
I think that it was "stuck" - looks good now. Thank you!!

**Comment by thinkingserious** [comment]
Hello @mptap,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
