### PR TITLE
Corrected spellings and punctuation for flow and consistency

### PR DESCRIPTION
**Pull request by s-Hale**
# Fixes # 

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified
- [x] I acknowledge that all my contributions will be made under the project's license

### Short description of what this PR does:
- Correction of spelling and grammar, including correct capitalisation of SendGrid, for flow and consistency. 
- 

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/nodejs-http-client?pullRequest=105) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/nodejs-http-client?pullRequest=105) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/nodejs-http-client?pullRequest=105) it.</sub>

**Comment by dagolinuxoid** [comment]
@s-Hale I like your corrections.

**Comment by thinkingserious** [comment]
Hello @s-Hale,

I'm re-opening this one because it's still in our queue for code review.

**Comment by s-Hale** [comment]
OK, thanks. There may be an issue with me signing the CLA, though, as I have a suspicion I accidentally committed the changes under a work email address I no longer have access to, which is why it seems to be preventing me from signing it. I can no longer add it to my Github addresses. Not sure how to get around it.

**Comment by thinkingserious** [comment]
Hello @s-Halel,

Just please add the following to the checklist (and fill in the check box) at the top of this PR:

- [ ] I acknowledge that all my contributions will be made under the project's license

Thanks!

With Best Regards,

Elmer

**Pull request closed without merging**
