### PR TITLE
Added esdoc

### PR DESCRIPTION
**Pull request by maxtotterman**
Added esdoc as proposed in #42  issue.

* Saved the libraries in dev dependencies instead.
* Added both documentations to CONTRIBUTING.md file since USAGE.md didn't exist.

Let me know if there should be any corrections.

Closes: #42

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/nodejs-http-client?pullRequest=44) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/nodejs-http-client?pullRequest=44) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/nodejs-http-client?pullRequest=44) it.</sub>

**Comment by maxtotterman** [comment]
Should be ok now.

**Comment by mbernier** [comment]
W00t!

**Comment by thinkingserious** [comment]
Hello @maxtotterman,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
